version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082" # or whatever port your Spring Boot app uses
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/transaction-database # Use 'db' for the database service hostname
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root


  db:
    image: postgres:latest
    ports:
      - "5432:5432" # Only necessary if you want to access the database from your host
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: transaction-database
    volumes:
      - db_data:/var/lib/postgresql/data


#  pgadmin:
#    image: dpage/pgadmin4:latest
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_LISTEN_PORT: 5050
#    ports:
#      - '5050:5050'

volumes:
  db_data: